/**
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * VisionGlass相关参数
 */
export class VisionGlassConstants {
  /**
   * 是否已连接vision glass设备
   */
  public static readonly CONNECT_VISION_GLASS: string = 'isConnectVisionGlass';
  /**
   * 是否显示在vision glass设备
   */
  public static readonly SHOW_IN_VISION_GLASS: string = 'showInVisionGlass';
  /**
   * VisionGlass vendorId
   */
  public static readonly VISION_GLASS_VENDOR_ID: string = '18455';
  /**
   * VisionGlass productId
   */
  public static readonly VISION_GLASS_PRODUCT_ID: string = '16962';
}