/**
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CallSettingSingleConstant {
  public static CLONE_PUBLIC_BACKUP_FIRST = 'comandroidservertelecomcallmanagerbackup';
  public static CLONE_PUBLIC_BACKUP_LAST = '_tb';
  public static LOCALE: string = 'Locale';
  public static CANNED_RESPONSE_PREF_FIRST: string = 'canned_response_pref_1';
  public static CANNED_RESPONSE_PREF_SECOND: string = 'canned_response_pref_2';
  public static CANNED_RESPONSE_PREF_THIRD: string = 'canned_response_pref_3';
  public static CANNED_RESPONSE_PREF_FOURTH: string = 'canned_response_pref_4';
  public static QUERY_PAGE_NUM = 200;
}