/**
 * Copyright (c) 2024-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 *  cust constants package tool class
 */

export class CustConstants {

  // cust parameters
  public static readonly VOLTE_SUPPORTED_BOOL = 'volte_supported_bool';
  public static readonly HIDE_IMS_SWITCH_BOOL = 'hide_ims_switch_bool';
  public static readonly CARRIER_NETWORKMODE_HIDE_BOOL = 'carrier_networkmode_hide_bool';
  public static readonly CARRIER_LTE_SWITCH_BOOL = 'carrier_lte_switch_show_bool';
  public static readonly CARRIER_NR_SWITCH_SHOW_BOOL = 'carrier_nr_switch_show_bool';
  public static readonly DATA_ROAMING_OPTION = 'hw_data_roam_option_int';
  public static readonly VALID_ROAMING_VALUES = ['0', '1', '2'];
  public static readonly VOWIFI_SUPPORTED_BOOL = 'vowifi_supported_bool';
}