/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export class AVRecorderConstant {
  // audio bit rate
  public static AUDIO_BITRATE: number = 100000;
  // number of audio channels
  public static AUDIO_CHANNELS: number = 1;
  // audio sampling rate
  public static AUDIO_SAMPLE_RATE: number = 48000;
  // Audio input source. Set this parameter to the call microphone.
  public static AUDIO_SOURCE_TYPE: number = 4;
}