/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export class CallSettingConstant {
  // Recording On
  public static OPEN_RECORDING_STATUS: number = 1;
  // Recording Off
  public static CLOSE_RECORDING_STATUS: number = 0;
  // All recordings
  public static RECORDING_WAY_ALL_NUMBER: string = '1';
  // Recording by a specified number
  public static RECORDING_WAY_DESIGNATE_NUMBER: string = '2';
}