/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const KEY_BOARD_SHOW: string = 'keyboard_show'
export const KEY_BOARD_HIDE: string = 'keyboard_hide'

export const CHAT_ITEM_ADD = 'chat_item_add'

export const KEY_RECEIVE_MESSAGE = 'message'
export const KEY_L2ID = 'l2Id'

export const INVALID_L2ID = -1

export const KEY_IS_CALL_ABILITY_FOREGROUND = 'is_call_ability_foreground'